### PR TITLE
Update winapi from 0.2 to 0.3

### PR DESCRIPTION
**Pull request by tchebb**
The new version has been out for a while now. Updating reduces version conflicts with downstream packages and also reduces compile time.

### CODE REVIEW

**Comment by oconnor663** [comment]
Thank you! This saves me a lot of trouble. Am I right in thinking that because we don't expose any of these types in our API, we can publish this with just a patch version bump?

**Comment by tchebb** [comment]
@oconnor663 I believe that's correct.

**Comment by oconnor663** [comment]
Just published 0.6.1.

**Comment by oconnor663** [comment]
I'll probably want to give similar treatment to https://github.com/oconnor663/shared_child.rs.

**Pull request merged**
