### PR TITLE
feat: Added visionOS support for Apple Vision Pro

### PR DESCRIPTION
**Pull request by eugenehp**
Tested it with [Tier 3](https://github.com/rust-lang/rust/pull/121419) target.

### CODE REVIEW

**Comment by oconnor663** [comment]
Thanks! Do you need this released to crates.io sooner rather than later?

**Comment by eugenehp** [comment]
Thanks for quick turnaround, Jack. Next scheduled release should be fine. 
We're still working on merging other PRs in the ecosystem.

**Comment by oconnor663** [comment]
I went ahead and published v1.2.0, along with some other cleanup I'd been meaning to do.

**Comment by eugenehp** [comment]
Awesome and thank you!

**Pull request merged**
